<?php

namespace ITRLibraryBundle\Repository;

/**
 * PostRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPostsSince(\DateTime $date)
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('p')
            ->from('ITRLibraryBundle:Post', 'p')
            ->where('p.createdAt > :date')
            ->andWhere('p.votes > -5')
            ->setParameter('date', $date->format('Y-m-d'));

        return $qb->getQuery()->getResult();
    }
}
