<?php

namespace ITRLibraryBundle\Repository;

/**
 * TagRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUnusedTags()
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('t')
            ->from('ITRLibraryBundle:Tag', 't')
            ->leftJoin('t.posts', 'p')
            ->where($qb->expr()->isNull('p.id'));

        return $qb->getQuery()->getResult();
    }
}
